---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chevo.
--- DateTime: 1/4/2024 4:22 PM
---
local function print_user_input()
	io.write("Enter your name: ")
	local name = io.read()
	io.write("Enter your age: ")
	local age = io.read()
	print("Hello, " .. name .. "!")
	print("Your age is " .. age .. ".")
end

local function main()
	print_user_input()
end

main()